---
title: "Rose am Wörthersee"
subtitle: "Comparative analyses of rowing gps tracks"
author: "by Michele Adamoli"
date: "`r Sys.time()`"
output:
  html_document:
    code_folding: hide
---

# Introduction

The aim of this script is to produce a map comparing rowing GPS-tracks.

```{r}

# Libraries

library(pacman)

p_load("tidyverse",
       "lubridate",
       "janitor",
       "DT",
       "knitr")

p_load("ggnewscale", "ggsn", "osmdata", "sf", "z11")



# Options R markdown

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,  results = 'markup')



```


# Collect data

First, you need to collect data from the Speedcoach (NK). For the map you need gps-position for each individual stroke.


```{r}
# Files vector

vec_data <- paste0("input/speedcoach/", list.files("input/speedcoach"))

# Dummy tibble for data per stroke   


vec_name_per_stroke <- c(
    "interval" ,
    "distance_gps" ,
    "distance_imp" ,
    "elapsed_time" ,
    "split_gps" ,
    "speed_gps" ,
    "split_imp" ,
    "speed_imp" ,
    "stroke_rate" ,
    "total_strokes" ,
    "distance_stroke_gps",
    "distance_stroke_imp",
    "heart_rate",
    "power" ,
    "catch" ,
    "slip" ,
    "finish" ,
    "wash" ,
    "force_avg" ,
    "work" ,
    "force_max" ,
    "max_force_angle" ,
    "gps_lat" ,
    "gps_lon",
    "id"
)

vec_names <- setNames(rep("", length(vec_name_per_stroke)), vec_name_per_stroke)
data_stroke_0 <- as_tibble(t(vec_names))[0, ]

# Dummy for summary

vec_name_per_workout <- c(
    "interval" ,
    "total_distance_gps",
    "total_distance_imp",
    "total_elapsed_time",
    "avg_split_gps" ,
    "avg_speed_gps" ,
    "avg_split_imp" ,
    "avg_speed_imp" ,
    "avg_stroke_rate" ,
    "total_strokes" ,
    "distance_stroke_gps",
    "distance_stroke_imp",
    "avg_heart_rate" ,
    "avg_power" ,
    "avg_catch" ,
    "avg_slip" ,
    "avg_finish" ,
    "avg_wash" ,
    "avg_force_avg" ,
    "avg_work" ,
    "avg_force_max" ,
    "avg_max_force_angle",
    "start_gps_lat" ,
    "start_gps_lon",
    "id"
)

vec_names <- setNames(rep("", length(vec_name_per_workout)), vec_name_per_workout)
data_sum_0 <- as_tibble(t(vec_names))[0, ]

# Loop

for (i in 1:length(vec_data)) {
    
    # # Metadata
    # 
    # meta_data <- read_csv(vec_data[i], col_names = FALSE)
    # workout <- meta_data[2, 2] %>% pull()
    # id <- meta_data[3, 2] %>% pull()
    # 
    # time_m <- str_sub(id, 15, 16)
    # 
    # time_h <- str_sub(id, 12, 13)
    # 
    # time <- if (as.numeric(time_h) > 12) {
    #     paste0(str_pad(string = as.character(as.numeric(time_h) - 12),
    #                    width = 2, side = "left", pad = "0"), time_m, "PM")
    # } else if (time_h == "12") {
    #     paste0(12, time_m, "PM")
    # } else {
    #     paste0(time_h, time_m, "AM")
    # }
    # 
    # time_mm <- str_sub(id, 1,2)
    # time_dd <- str_sub(id, 4,5)
    # time_yy <- str_sub(id, 7,10)
    # 
    # date <- paste0(time_dd, "/", time_mm, "/", time_yy)
    # 
    # Data per stroke
    
    data_stroke <- read_delim(vec_data[i], 
                              delim = ",", 
                              col_names = TRUE, 
                              skip = 28,
                              col_type = paste(rep("c", 27), collapse = "")) %>% 
        clean_names() %>% 
        filter(interval != "(Interval)") %>% 
        mutate(id = str_sub(vec_data[i], start = 18, end = -5))
        
    # # Data summary 
    # 
    # data_sum <- read_delim(vec_data[i], delim = ",",
    #                        col_names = TRUE,
    #                        skip = 20,
    #                        col_type = paste(rep("c", 27), collapse = "")) %>% 
    #     clean_names()
    # 
    # n_interval <- which(data_sum$interval == "Per-Stroke Data:")
    # 
    # data_sum <- data_sum[2:(n_interval - 1),] %>% 
    #    mutate(id = id) %>% 
    #    mutate(date = date) %>% 
    #    mutate(time = time) %>% 
    #    mutate(workout = workout)
    #     
    # Finalise
    
    data_stroke_0 <- bind_rows(data_stroke , data_stroke_0) 
    # data_sum_0 <- bind_rows(data_sum , data_sum_0)
    
}


```

# Wörthersee map

This map shows the tracks on the water. The Wöthersee maps comes from openstreetmap.org.

```{r}

# Get OSM data for the specified area

woerthersee_sf <-
  osmdata::getbb(place_name = "Wörthersee") %>% 
  osmdata::opq(timeout = 25*100) %>%
  osmdata::add_osm_feature(key = 'natural', value = 'water') %>% 
  osmdata::osmdata_sf() %$% 
  osm_multipolygons %>% 
  dplyr::select(geometry)

# Prepare gps data

gps_data_0 <- data_stroke_0 %>% 
  mutate(across(c("gps_lat", "gps_lon"), ~as.numeric(.)))

# Plot area and gps data

p <- ggplot(woerthersee_sf) +
  geom_sf(fill = "white") +
  ggsn::blank() +
  geom_line(data = gps_data_0, aes(x = gps_lon, y = gps_lat, color = id), size = 0.25) +
  theme(legend.position = "bottom") +
  theme(legend.title = element_blank())

# Show and save

p

ggsave(plot = p, filename = "output/gps_woerthersee.png", dpi = 450)


```


